instanceSecret: "130892-aSLaockNV91-IOAjsddjsws"
rootPrefix: "insi-db-rpfx-89024KKS903asSDsa112="

defaultLeader: "db0"

insudbDir: "/home/bosley/.config/insi"

tls:
  cert: /etc/letsencrypt/live/insula.dev/fullchain.pem 
  key: /etc/letsencrypt/live/insula.dev/privkey.pem

clientSkipVerify: false
serverMustUseTLS: true

cache:
  standard-ttl: 60m
  keys: 1m

rateLimiters:
  values:
    limit: 100
    burst: 150 
  tags:
    limit: 50
    burst: 75
  cache:
    limit: 200
    burst: 250
  system:
    limit: 10
    burst: 20
  default:
    limit: 5
    burst: 10
  events:
    limit: 500
    burst: 750

sessions:
  eventChannelSize: 256
  webSocketReadBufferSize: 1024
  webSocketWriteBufferSize: 1024
  maxConnections: 1000


nodes:
  db0:
    raftBinding: 10.116.0.27:2222
    httpBinding: 134.122.121.148:443
    clientDomain: "db-0.insula.dev"
    nodeSecret: "db0-secret"
  db1:
    raftBinding: 10.116.0.25:2222
    httpBinding: 143.198.113.110:443
    clientDomain: "db-1.insula.dev"
    nodeSecret: "db1-secret"
  db2:
    raftBinding: 10.116.0.26:2222
    httpBinding: 142.93.119.59:443
    clientDomain: "db-2.insula.dev"
    nodeSecret: "db2-secret"